site_tourneur_fraiseur_homepage:
    path:     /
    defaults: { _controller: SiteTourneurFraiseurBundle:Default:index }
    
espaceCandidat:
    path:	 /EspaceCandidat
    defaults: {_controller: SiteTourneurFraiseurBundle:Annonce:EspaceCandidat}

inscription:
    path:	 /Inscription
    defaults: {_controller: SiteUserBundle:Default:index}
    
registration_ok:
    path:	 /InscriptionConfirm√©
    defaults: {_controller: SiteUserBundle:Default:inscriptionComplete}

Espace:
    path:	 /MonEspace
    defaults: {_controller: SiteTourneurFraiseurBundle:Default:monEspace}

#																	Utilisateur

recruteur_modif:
    path:	 /ModificationInformationsPersonnelles
    defaults: {_controller: SiteTourneurFraiseurBundle:Utilisateur:change}
    